### ISSUE TITLE
导出pdf的问题关于加粗倾斜字体

### ISSUE THREAD

**Issue by dalang0414** [du33169/typora-theme-essay_cn#5]
作者，你好。使用您的主题时，在Typora内加粗和倾斜字体时正常显示的，但是导出为pdf后，加粗和倾斜就无效了

**Comment by du33169** [comment]
我这里是正常的，能否提供一下你使用的操作系统、typora版本和最简的md源文件？
以及是直接在Typora导出还是转成HTML或者pandoc之类的其他途径？

**Comment by dalang0414** [comment]
你好。我用的是win10系统，typora版本是0.11.18。然后直接在typora导出成pdf文件的
![image](https://user-images.githubusercontent.com/63236643/150628325-d0565226-f9df-43b1-97b4-c5d7fc6f76cc.png)
导出之后变成了
![image](https://user-images.githubusercontent.com/63236643/150628338-1c965daa-1fbc-438b-8a48-b13b6bc9e6e8.png)

**Comment by pluveto** [comment]
同样的问题

**Comment by du33169** [comment]
这个问题是Typora在Windows上的字体渲染逻辑bug造成的，目前发现尤其是“宋体”等字体会造成这一问题。
Typora在最近的更新中（v1.5.8）修复了这一问题，可以将typora更新到最新版以解决

如果仍在使用beta或其他旧版本，有两种方法：
- 手动将css中的宋体换成“华文中宋”（参考[该issue](https://github.com/Keldos-Li/typora-latex-theme/issues/74)），
- 手动定义不同font-weight时使用的font-face（参考[该博文](https://pku-zyf.github.io/typora/)）
