### ISSUE TITLE
Cover fonts bug

### ISSUE THREAD

**Issue by ghost** [du33169/typora-theme-essay_cn#6]
typora: Version 1.6.7 (6865)
OS: macOS Ventura 13.4

使用仓库默认的 `essay_sample` 模板，typora 编辑界面预览是正常的，但是使用默认的导出为 PDF 功能，封面字体显示如下：

<img width="1101" alt="image" src="https://github.com/du33169/typora-theme-essay_cn/assets/45538642/bee0254b-fc7c-4ca5-bbb9-cc873ddd1b40">

希望作者有空可以排查一下这个问题，谢谢！

**Comment by du33169** [comment]
能否上传一份使用导出HTML功能生成的HTML？

看上去像是第一列的宽度小了，目前版本是手动设置的width样式，我找时间更新一下布局。

**Comment by ghost** [comment]
我用windows上的 typora 测试了一下，确实是正常的，macOS 自己改一下宽度就好了，谢谢解答。
