### ISSUE TITLE
用word命令行导出报错

### ISSUE THREAD

**Issue by Liu8Can** [du33169/typora-theme-essay_cn#8]
显示文件不存在
pandoc -i xxx.md --reference-doc word_ref.docx xxx.docx
请问word_ref.docx 这个文件要放到哪里？

**Comment by du33169** [comment]
替换为你的实际路径。如果直接这样写是要求和md同一目录。
如果是clone的仓库，写完整成`[path to repo]/typora-theme-essay_cn/templates/Word_style/word_ref.docx`

是我写的简略了，有空更新一下README.md

**Comment by Liu8Can** [comment]
好滴~ 谢谢！
